
# for clustering
min_samples: 1

# eps params for time/dm clustering
eps:
  total_sample: 3
  dm: 5
#  boxc_width: 4

# eps params for space clustering (second layer)
eps2:
  lpix: 3
  mpix: 3

# candidates classify
threshold:
  lpix_rms: 2           # minimum threshold for a RFI clustering
  mpix_rms: 2
  num_samps: 2          # number of samples for each cluster - one metric for RFI classification
  num_spatial: 2        # number of spatially coherent clusteres in each space/time clusters
  max_snr: 50           # if the SNR is larger than the threshold, then it's not classified as RFI even it satisfies above metric
  mSlope: 1             # m6, for m6>1 select the first two brightest spatial clusters
  mSlopeSmooth: 0.04    # selection metrics - if 0 <= m7 < 0.04 then it can be a real source
  mSNR: 0.2             # selection metrics - rule out all candidates with m3 < 0.2 (they're just some kind of weird RFIs)
  num_mSlopeSmooth: 10  # using first 10 data points to do smooth

filter_radius: 2 # in unit of degree - only select catalogue candidates within this radius

# location for pulsar/RACS/new sources catalogue csv
# use the same catalogue for alias checking 
# ordered by priority, i.e. if one object is in multiple catalogues we will use the lastest catalogue as classification 
catpath: [
  '/home/craftop/share/racscat_gaussian_0.3Jy.csv',  # RACS 
  '/home/craftop/share/atnf_psrcat_localized.csv',  # PSR
  '/home/craftop/share/craco_updated.csv',           # CUSTOM
]
catcols:
  ra: ['RA', 'RAJD', 'RAD']
  dec: ['Dec', 'DECJD', 'DECD']
  input_colname: ['Gaussian_ID', 'PSRJ', 'NAME']
  output_prefix: ['RACS', 'PSR', 'CUSTOM']

threshold_crossmatch: [60, 60, 60] # in unit of arcsec

# for injection
inject_tol:
  srcsep: 60 # in unit of arcsec
  tsmaps: 10 # pixel
  dm_pccm3: 20 # in physical units
  dm_frac: 0.1 #in percentage of dm

# dataframe format
dformat:

  colfloat:
    snr: 1
    obstime_sec: 4
    mjd: 9
    dc_pccm3: 3
    ra_deg: 5
    dec_deg: 5
    mSNR: 3
    mSlope: 3
    mSlopeSmooth: 3
    # lpix_rms: 3
    # mpix_rms: 3
    # centl: 2
    # centm: 2

  colint: [
    'lpix',
    'mpix',
    'boxc_width',
    'time',
    'dm',
    'iblk',
    'rawsn',
    'total_sample',
    'ibeam', 
    'cluster_id',
    'spatial_id',
    'num_samps',
    'num_spatial',
    ]

