
# for clustering 
min_samples: 1 

# eps params for time/dm clustering
eps:
  total_sample: 3
  dm: 5
  boxc_width: 4

# eps params for space clustering (second layer)
eps2:
  lpix: 3
  mpix: 3

# candidates classify 
threshold:
  lpix_rms: 2 # minimum threshold for a RFI clustering 
  mpix_rms: 2
  num_samps: 2 # number of samples for each cluster - one metric for RFI classification
  num_spatial: 2 # number of spatially coherent clusteres in each space/time clusters
  max_snr: 100 # if the SNR is larger than the threshold, then it's not classified as RFI even it satisfies above metric 


filter_radius: 2 # in unit of degree - only select catalogue candidates within this radius 

# location for pulsar/RACS catalogue csv
catpath: ['/data/fast/wan342/dash-craco-cand-dep/data/atnf_psrcat_localized.csv', 
          '/data/fast/wan342/dash-craco-cand-dep/data/racs_bright_1.0Jy.csv', 
          '/data/big/craco/wan348/catalogues/craco_updated.csv']
catcols: 
  ra: ['RAJD', 'RA', 'RAD']
  dec: ['DECJD', 'Dec', 'DECD']
  input_colname: ['PSRJ', 'Gaussian_ID', 'NAME']
  output_prefix: ['PSR', 'RACS', 'NEW']

threshold_crossmatch: [60, 60, 60] # in unit of arcsec 
