#!/bin/bash

# Deletes a schedblock
# Inputs should not have a prefix
# e.g. SB046779/targets/NoDrive
# it should start with SB and the entire SB will be delete



for sb in $@ ; do
    if [[ $sb == SB* ]] ; then
	sbdir=$(echo $sb | cut -d/ -f 1)
	fullpath="/data/seren*/big/craco/$sbdir"
	echo Deleting $fullpath
	rm -Rf $fullpath
    else
	echo "Supplied SB doesnt start with SB: $sb. Continuing"
	continue
    fi

done
